// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE_coZf-gPTMe-7SHcgVEtVhW1GF820D0',
    appId: '1:932182431521:web:0d524370c2e93f2b755060',
    messagingSenderId: '932182431521',
    projectId: 'testauth-df1a9',
    authDomain: 'testauth-df1a9.firebaseapp.com',
    storageBucket: 'testauth-df1a9.appspot.com',
    measurementId: 'G-96DZWR8TCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHhgf5_TMWQnu2q5cU7cMBrIT6thZXOFA',
    appId: '1:932182431521:android:6333762b09a9c4e1755060',
    messagingSenderId: '932182431521',
    projectId: 'testauth-df1a9',
    storageBucket: 'testauth-df1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzVMLFLecWY-XHqS0dkKS7CbnOG2vFlgE',
    appId: '1:932182431521:ios:bd8b51b2348ce927755060',
    messagingSenderId: '932182431521',
    projectId: 'testauth-df1a9',
    storageBucket: 'testauth-df1a9.appspot.com',
    iosBundleId: 'com.example.test50505050',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzVMLFLecWY-XHqS0dkKS7CbnOG2vFlgE',
    appId: '1:932182431521:ios:45f4b52c5da59257755060',
    messagingSenderId: '932182431521',
    projectId: 'testauth-df1a9',
    storageBucket: 'testauth-df1a9.appspot.com',
    iosBundleId: 'com.example.test50505050.RunnerTests',
  );
}
